/******  Table [dbo].[Countries]  ******/
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE Table_Name='Categories')
CREATE TABLE dbo.Categories(
CategoryId		BIGINT	IDENTITY(1,1)	NOT NULL,
CategoryCode	VARCHAR(10)				NOT NULL	CONSTRAINT AK_CategoryCode UNIQUE(CategoryCode) ,  
Category		VARCHAR	(25)			NOT NULL	CONSTRAINT AK_Category UNIQUE(Category) ,  
Status	BIT		NOT NULL
CONSTRAINT PK_Categories PRIMARY KEY CLUSTERED
(
CategoryId ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO